version: '3.8'

services:
  main:
    container_name: main
    build:
      context: .
    environment:
      PORT: ${PORT}
      PRIVATE_KEY: ${PRIVATE_KEY}
      WEATHER_TOKEN: ${WEATHER_TOKEN}
    volumes:
      - .:/app
      - /app/node-modules
    ports:
      - 5005:5005
    command: npm run start:dev
    depends_on: 
      - postgres
    restart: always
  
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    ports: 
      - ${POSTGRES_PORT}:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
